### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by patrickbergner** [mraible/jhipster8-demo#1]
Seems like all the stuff in the `static` directory was missed uploading, including all images. Please fix if possible.

**Comment by mraible** [comment]
This tutorial is still in progress. I'm waiting on an 8.0.1 release because I found a [bug](https://github.com/jhipster/generator-jhipster/issues/24125).

**Comment by mraible** [comment]
All images are now present. Thanks for keeping me honest!
