### ISSUE TITLE
entities not reflected in webpage

### ISSUE THREAD

**Issue by djsg** [mraible/jhipster8-demo#209]
Hi Matt,

I followed your steps and managed to create a working blog webapp.
However, I stuck at adding blog entities. I ran "jhipster jdl blog.jdl", say yes to all overwrites, and restart blog app.
After admin login, the entities tab is still empty.

**Comment by mraible** [comment]
@djsg What version of JHipster are you using? Can you try these steps and see if it works:

```
git clone https://github.com/mraible/jhipster8-demo
cd jhipster8-demo
rm -rf *
jhipster
```

This will re-generate the app with whatever version you're using and you should be able to start it with Maven.

**Comment by djsg** [comment]
Hi Matt,
I did as you suggested. The demo code works perfectly fine.
This time I used a computer with Ubuntu OS; previously all my experiments were tried in Windows machine.
Does OS make such a big diff?

**Comment by mraible** [comment]
@djsg The OS shouldn't matter, but we do tend to test things on macOS and Linux more than Windows.
