### ISSUE TITLE
Cannot Locate the methods findByUserIsCurrentUser() and findAllWithToOneRelationships()

### ISSUE THREAD

**Issue by kdjomeda** [mraible/jhipster8-demo#41]
I am using jhipster 8.1.0 and following the tutorial to this repo at https://www.youtube.com/watch?v=IfyjKCt6YHE&t=236s.

I did create manually the findByUserIsCurrentUser() as it's straight forward. However the `findAllWithEagerRelationships()` isn't using at all the findAllWithToOneRelationships().

Below is the generated code from BlogRepository.java
```java
@Repository
public interface BlogRepository extends ReactiveCrudRepository<Blog, Long>, BlogRepositoryInternal {
    @Override
    Mono<Blog> findOneWithEagerRelationships(Long id);

    @Override
    Flux<Blog> findAllWithEagerRelationships();

    @Override
    Flux<Blog> findAllWithEagerRelationships(Pageable page);

    @Query("SELECT * FROM blog entity WHERE entity.user_id = :id")
    Flux<Blog> findByUser(Long id);

    //This was added by following the tutorial
    @Query("select blog from Blog blog where blog.user.login = ?#{authentication.name}")
    Flux<Blog> findByUserIsCurrentUser();
   // ...
}
```

Where to add the "#{authentication.name}" condition for the eager loading?

**Comment by mraible** [comment]
It looks like you're using Spring WebFlux instead of Spring MVC. The tutorial and video uses Spring MVC.

**Comment by kdjomeda** [comment]
Oops thank you, I will switch to the spring MVC then.
